# Generated by Django 2.2.20 on 2021-04-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='arguments_as_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
