# Generated by Django 2.2.20 on 2021-04-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cog', '0002_auto_20210420_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='prevent_overlapping_runs',
            field=models.BooleanField(default=True),
        ),
    ]
