# Generated by Django 2.2.20 on 2021-04-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cog', '0003_pipeline_prevent_overlapping_runs'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
