# Generated by Django 2.2.20 on 2021-04-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cog', '0004_task_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='proceeds',
        ),
        migrations.AddField(
            model_name='stage',
            name='launch_after_stage',
            field=models.ManyToManyField(blank=True, null=True, related_name='next_stage', to='django_cog.Stage'),
        ),
    ]
