# Generated by Django 2.2.20 on 2021-04-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cog', '0005_auto_20210426_0819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['pipeline', 'name']},
        ),
        migrations.AlterField(
            model_name='stage',
            name='launch_after_stage',
            field=models.ManyToManyField(related_name='next_stage', to='django_cog.Stage'),
        ),
    ]
