# Generated by Django 2.2.28 on 2023-03-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cog', '0018_auto_20210915_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinerun',
            name='success',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='stagerun',
            name='success',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='taskrun',
            name='success',
            field=models.BooleanField(null=True),
        ),
    ]
